services:
  aniworld-downloader:
    image: ghcr.io/m4rc-xx/aniworld-downloader-docker:next
    container_name: aniworld-downloader
    tty: true
    stdin_open: true
    volumes:
      - /home/pi/aniworld-downloads:/app/downloads #Path to yout downloads folder
    restart: unless-stopped
